-- SQLDash instance registry — NATIVE PostgreSQL (assigns the integer instance_id key).
--
-- This is NOT a DuckLake table. It is a regular Postgres table whose IDENTITY sequence mints
-- instance_id (starting at 1000, matching the legacy dbo.Instance identity), with get-or-create
-- semantics on a UNIQUE instance_fqn label. The lake's common.instances is the analytical copy;
-- THIS is the operational source of truth, and it additionally carries connect_target — the
-- host[,port] the collector actually dials. connect_target is intentionally NOT unique: many
-- registry rows may point at the same host (e.g. the bench seeds 1000 rows all targeting localhost),
-- while instance_fqn stays the unique identity so the integer key space is sane.
--
-- Lives in the bench catalog db for the spike; production co-locates it with sqldash_catalog.

CREATE SCHEMA IF NOT EXISTS registry;

CREATE TABLE IF NOT EXISTS registry.instances (
    instance_id    INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    instance_fqn   TEXT        NOT NULL UNIQUE,                 -- identity label (get-or-create key)
    instance_name  TEXT,
    platform       TEXT        NOT NULL DEFAULT 'sqlserver',
    connect_target TEXT        NOT NULL,                        -- host[,port] to dial (may repeat)
    auth_mode      TEXT        NOT NULL DEFAULT 'integrated',   -- 'integrated' | 'sql'
    environment    TEXT        DEFAULT 'P',
    status         TEXT        DEFAULT 'a',
    registered_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ
);

-- get-or-create: returns the (possibly newly minted) instance_id for a normalized fqn.
-- Idempotent — a second call with the same fqn returns the existing id and refreshes connect_target.
CREATE OR REPLACE FUNCTION registry.get_or_create_instance(
    p_fqn            TEXT,
    p_connect_target TEXT,
    p_platform       TEXT DEFAULT 'sqlserver',
    p_name           TEXT DEFAULT NULL,
    p_auth_mode      TEXT DEFAULT 'integrated',
    p_environment    TEXT DEFAULT 'P',
    p_status         TEXT DEFAULT 'a'
) RETURNS INTEGER
LANGUAGE plpgsql AS $$
DECLARE v_id INTEGER;
BEGIN
    INSERT INTO registry.instances
        (instance_fqn, instance_name, platform, connect_target, auth_mode, environment, status)
    VALUES
        (p_fqn, COALESCE(p_name, p_fqn), p_platform, p_connect_target, p_auth_mode, p_environment, p_status)
    ON CONFLICT (instance_fqn) DO UPDATE
        SET connect_target = EXCLUDED.connect_target,
            updated_at     = now()
    RETURNING instance_id INTO v_id;
    RETURN v_id;
END;
$$;
